version: '3'

services:
  frontend:
    build:
      context: ./frontend
    image: frontend-test
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"

  postgres:
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: docker-intro
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
    image: backend-test
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

volumes:
  db-data: